[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyquicktli"
version = "0.1.0"
description = "Py Quick TLI is a utility tool for quickly creating CLI / TLI functionality."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name="Logan Boehm", email="me@logan-boehm.com" }
]
dependencies = ["curses"]

[project.urls]
Homepage = "https://github.com/lganic/Py-Quick-TUI/main"

[tool.setuptools.packages.find]
where = ["."]
include = ["pyquicktli"]
